### ISSUE TITLE
Issue with accessing children with NanoEvents after .compute()

### ISSUE THREAD

**Issue by rkansal47** [scikit-hep/coffea#1200]
**Describe the bug**

If I try to access the children of an object loaded as a dask_awkward array and then computed I get the error:

```python
File ~/mambaforge/envs/python311/lib/python3.11/site-packages/coffea/nanoevents/methods/nanoaod.py:139, in GenParticle.children(self)
    133 @dask_property
    134 def children(self):
    135     """
    136     Accessor to direct children of this particle (not grandchildren). Includes particles
    137     with the same PDG ID as this particle.
    138     """
--> 139     return self._events().GenPart._apply_global_index(self.childrenIdxG)

File ~/mambaforge/envs/python311/lib/python3.11/site-packages/coffea/nanoevents/methods/base.py:270, in NanoCollection._events(self)
    268 if "@original_array" in self.attrs:
    269     return self.attrs["@original_array"]
--> 270 return self.attrs["@events_factory"].events()

KeyError: '@events_factory'
```

with coffea 2024.10.0 awkward 2.6.9.

**To Reproduce**
MRE:

```python
events_delayed = nanoevents.NanoEventsFactory.from_root(
    {
        "root://cmseos.fnal.gov///store/user/lpcpfnano/cmantill/v2_3/2017/HH/GluGluToHHTobbVV_node_cHHH0_TuneCP5_13TeV-powheg-pythia8/GluGluToHHTobbVV_node_cHHH0/220808_163755/0000/nano_mc2017_1-1.root": "Events"
    },
    schemaclass=nanoevents.NanoAODSchema,
    delayed=True,
).events()

higgs = events_delayed.GenPart[events_delayed.GenPart.hasFlags(["fromHardProcess", "isLastCopy"]) * (events_delayed.GenPart.pdgId == 25)]
print(higgs.compute().children)
```

**Comment by lgray** [comment]
The issue here is that the self-reference to the original events is lost when you compute (because you can't recursively compute a dask array!). So this isn't actually a bug but rather a consequence of how dask works.

I would suggest instead using `delayed=False` and doing your data exploration with completely eager nanoevents on that single file or you can try `higgs.children.compute()` and then work with that array (which you will not be able to recurse through.

Or if you know what you're looking for you can work with the dask array itself and then only compute what you want.

**Comment by rkansal47** [comment]
I see. For context, I was trying to compute earlier than needed as a workaround for #1199, i.e., trying to flatten `higgs.children.compute().children` instead of `higgs.children.children` which gives an error.

**Comment by lgray** [comment]
@rkansal47 So we can bring this to a close now that the originating issue is fixed up. I think the correct course of action is to have in the documentation or otherwise advertised to the user that crossing the delayed-to-eager "boundary" causes some loss of functionality. 

In fact, I would say maintaining that functionality (all the cross references working and such) probably leads to some strange or inefficient workflows. You could imagine someone settling on computing the who gen particles list and doing the rest of an analysis locally, in a bad situation.

Dealing with all the possible ways I'd have to configure eager NanoEvents to work correctly given a user's possible manipulations when then doing `.compute()` on a delayed NanoEvents can't really be done in a way that doesn't ever evoke confusion (that I can think of). 

At the very least it fails now, which is the correct thing to do, but doesn't explain itself. However, without context it leads to confusion. I think the first thing I'll do is make it so that if you hit the case where the original array generator isn't available that the error message makes it clear what's going on and why.

**Comment by lgray** [comment]
Is there anything else you'd want? Given that making it work in all cases is extremely difficult and/or impossible.

**Comment by rkansal47** [comment]
Thank you for the bug fix @lgray! Yeah, I think a clearer error message would be useful. Apart from that, I agree that this functionality is unnecessary (I would actually prefer delaying the `.compute()` to the end whenever possible).
