### ISSUE TITLE
Specify a per-module array backend (numpy or cupy) for modules

### ISSUE THREAD

**Issue by jpata** [scikit-hep/coffea#133]
**Is your feature request related to a problem? Please describe.**
It can be useful to switch to a GPU-based backend such as cupy on a per-module basis without needing the whole coffea ecosystem to be ported. For example, factorized JEC uncertainty computation is mainly based on `interp1d` and lookups which are highly efficient on a GPU.

**Describe the solution you'd like**
Each module would have to carry a configurable backend option. A backend can be as simple as setting `JetCorrectionUncertainty.numpy_lib = numpy or cupy`), but due to a non-perfect feature parity between the two libraries and possible future alternatives, likely some simple backend class that can provide wrapping functionaly could be provided, e.g. `coffea.backends.NumpyBackend, CupyBackend`. The backend would either rely on the inputs being located on the correct device or do the transfer on the fly, depending on the design choice.

**Describe alternatives you've considered**
A switch can be made globally in `coffea.util.np`, but that is non-ideal before awkward-array works completely with another backend. A physics user may want to use only a part of the coffea library on a certain device.

**Additional context**
I've made a first attempt at converting the JEC code to a GPU in my fork https://github.com/jpata/coffea/pull/1. I've seen a performance improvement of roughly 7x (160s on a CPU vs 24s on a GPU) on computing factorized JEC on 10M random jets.

**Comment by lgray** [comment]
As pointed out, the main thing we need to consider here is that cupy's functionality is not the same as numpy's, especially for sorts and other higher level functions. 

Perhaps a reasonable solution can be implemented if we determine the missing functionality of cupy, populating a python file with it and then using that to wrap and otherwise interface with cupy.

There seems to be a bit of hidden hacks in cupy:
https://github.com/cupy/cupy/blob/master/cupy/statistics/histogram.py#L14
(for instance)
As to why they haven't just written search sorted, beats me...

Maybe something like coffea.utils.cupy which grabs everything from the cupy name space and sprinkles in the extras that we need? We can then pass that to `lookup_base` so it can be used as needed by the derived classes. This is sort of halfway between the two suggested and closer to how @jpivarski handles various awkward libraries in his stuff, which we may also want to emulate eventually.

**Comment by jpivarski** [comment]
In the original plans for awkward-cuda, I was thinking that I'd probably have to wrap CuPy because it might be lacking necessary features. That would be a non-ideal and hopefully temporary solution, though the set of things that need to be wrapped work as a wish-list for the CuPy developers. It looks like you might be running into it before me.

I haven't tried it, but I've heard that Numba is now CuPy aware, so you can write full CUDA kernels for CuPy arrays (more general than the kernel-writing functionality CuPy provides, which was only for ufunc-like functions—i.e. nothing that could sort—the last time I saw). Numba translates the entire CUDA programming model, including the block size and grid size details I'd rather not deal with, to Python. At least it would be better than swapping between Python and C++ for direct CUDA.

**Comment by lgray** [comment]
So, rather than a single library being specified we'd need some sort of "software stack" that can be specified as an argument to parts of `coffea`. 

It'd need to define the variant of a numpy-like backend, the flavor of awkward to use, as well as any necessary extensions to the numpy library to become feature complete. I suppose it would also have to specify the flavor of numba to use. I am not sure if trying to make things parameterized like this is better than just rewriting specialized libraries that are inter-operable sort of like what @jpivarski is doing.

Thoughts @jpata ?

**Comment by jpata** [comment]
Thanks both for your thoughts.

@jpivarski I've been able to accomplish everything that was necessary for physics analysis in CUDA so far with `@numba.cuda.jit` kernels (generic, not ufunc-based), not having to drop down to C++ for CUDA code. I'm really surprised at how easy it has been from the compilation and debugging point of view. As an example, here is the `mask_deltar_first` function: https://github.com/jpata/hepaccelerate/blob/master/hepaccelerate/backend_cuda.py#L271
I feel like a limited subset of awkward data structures (e.g. arrays with one level of nesting) and operations could be supported relatively easily given the proof-of-concept in my `hepaccelerate` demonstrator. I could contribute the code and tests if you are would be willing to suggest function stubs or a package structure that are suitable for your plans in `awkward` (we can take it into another issue).

@lgray I'm also unsure of what's better for the coffea/awkward/scikit-hep ecosystem as a whole...
In practice, for me and a few other emerging GPU enthusiasts, we start to already make use of and extend coffea with the relevant GPU tools with good results. I agree that having a lot of half-baked solutions in a commonly used library is perhaps not very productive, so it might be better to hold off on making coffea GPU-aware before e.g. awkward is able to support it. I will try to coordinate with the GPU enthusiasts such that we maintain a ~single fork with the GPU-relevant patches factorized for easier upstreaming later. If you are willing to consider a pluggable "backend" on a per-module basis as you suggest in the future, I believe this could be quite useful for coffea and for analysis.

Many thanks for coffea, awkward and your suggestions!
