### ISSUE TITLE
 Bitwise operations in Coffea

### ISSUE THREAD

**Issue by afrankenthal** [scikit-hep/coffea#140]
As discussed in the last meeting, an interesting use case might be doing bitwise-arithmetic in columnar format. Sometimes I pre-compute fancier cuts when running the ntuplizer over my AOD samples (e.g to use some of the CMSSW libraries), and save each cut into one bit of a uint32_t variable. If there's a way to build cutflows out of those bits this would be very convenient. Perhaps this is already possible with just the existing infrastructure?

Thanks!

**Comment by nsmith-** [comment]
Take a look at `coffea.processor.PackedSelection` in https://github.com/CoffeaTeam/coffea/blob/master/coffea/processor/helpers.py#L67
Maybe these helpers should be moved to a more obvious location.

**Comment by lgray** [comment]
@afrankenthal Yeah, with a bit of columnar bitwise manipulation you should be able to use a packed selection. It works just like typical bitwise manipulation in python or C++. 

If you don't need to collapse any selections together you can probably just toss your packed bytes directly in.

@nsmith- Either a more obvious location or an example in the binder would be sufficient I think? Also add it to the docs / examples.

**Comment by nsmith-** [comment]
PackedSelection has some [docs](https://coffeateam.github.io/coffea/api/coffea.processor.PackedSelection.html) now.  But I believe you are asking for a utility to help with interpreting a pre-existing packed selection rather than making a new one.  For that, something needs to be written still.  Nevertheless, you can do bit arithmetic in numpy as easily in C:
```python
import numpy as np
cut0 = np.random.randint(2, size=100).astype(bool)
cut1 = np.random.randint(2, size=100).astype(bool)
cut2 = np.random.randint(2, size=100).astype(bool)
packed = (cut0<<0) | (cut1<<1) | (cut2<<2)

unpacked_cut2 = (packed & (1<<2)).astype(bool)
np.all(unpacked_cut2 == cut2)
```
The same procedure works equally well on awkward arrays.
