### ISSUE TITLE
Saving recHits for columnar processing

### ISSUE THREAD

**Issue by afrankenthal** [scikit-hep/coffea#141]
Another interesting use case would be iterating over a recHits collection. In our analysis we try to match two different track reconstruction algorithms based on the ID of the hits in each object. This information is only in AOD (I believe), so right now this gets done at the ntuplizer level. But if it were possible to process it with a columnar approach, then I could maybe add the recHit information to the flat ntuples, using an index offset marker to separate hits belonging to different objects, as suggested by Nick (and similar to the structure of JaggedArrays themselves).

**Comment by nsmith-** [comment]
Here's another discussion regarding this topic: https://github.com/cms-nanoAOD/cmssw/issues/92#issuecomment-499284307

**Comment by lgray** [comment]
This issue seems like partially a feature request for for awkward array, partially for encoding in NanoAOD and then finally an implementation of an example for our binder here?

Just trying to factor out the responsibilities.

@jpivarski Couldn't this also be handled with a double-jagged array? If it was handled in a uproot-methods profile could it be made into a pretty slick interface so long as the dataformat in NanoAOD was agreed upon.

**Comment by jpivarski** [comment]
You can't put a (native) doubly jagged array on a ROOT file, but you can do the content + offsets you're proposing and then have it converted into a doubly jagged array with no loss in performance.

This sort of thing can be a profile, like the profiles in uproot-methods. There's one profile in there that converts `Muon_pt`, `Muon_eta`, etc. into `muons` that contain `pt`, `eta`, etc. Profiles do some processing on the raw data in a ROOT file to provide a different view with awkward-arrays.

**Comment by lgray** [comment]
long story short - do it with parquet :-)

**Comment by nsmith-** [comment]
There is a prototype RNTuple NanoAOD output module that might be worth exploring for such a case. It can save natively double-jagged data efficiently.
