### ISSUE TITLE
Workflows executing on forked repos

### ISSUE THREAD

**Issue by dntaylor** [scikit-hep/coffea#243]
The workflows are executing on my forked repo.
Is this expected? Is there a configuration I am missing to prevent github actions from occurring on a forked repo?

https://github.com/dntaylor/coffea/actions

**Comment by lgray** [comment]
I don't know how to enforce this by default but you can turn it off in your local fork if you look under settings.

@matthewfeickert ?

**Comment by matthewfeickert** [comment]
This isn't a bug, but rather just a choice.

As @lgray has mentioned, if you just remove the following lines in your local branch

https://github.com/CoffeaTeam/coffea/blob/2c23b1015371b9687013a6b607e387452443d66c/.github/workflows/ci.yml#L5-L6

then you'll be good to go. So it would now look like

```yaml
on:
  push:
  pull_request:
    branches:
      - master
  # Run daily at 0:01 UTC
  schedule:
    - cron:  '1 0 * * *'
```

Though you probably also want to make sure you give that commit a title like "DELETE ME: Remove master only on CI push events" so that you know before requesting a review to go ahead and drop that commit in your interactive rebase. That being said, for pyhf we just run on all branches and haven't ever really gotten to the point of being bottlenecked with GitHub Actions like we would get with Travis. :rocket:

**Comment by dntaylor** [comment]
Got it, didn't initially find it under the actions tab, where I expected it to be. But under repository settings.
