### ISSUE TITLE
Plot systematic uncertainties in plot1d and plotratio

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#332]
**Is your feature request related to a problem? Please describe.**
Currently `plot1d` and `plotratio` calculate the statistical uncertainties very nicely and plot them. However for most analyses, especially the ones that are dominated by systematic effects, it is crucial to also indicate the size of the systematic uncertainties. This is not easily possible with the current plot functions.

**Describe the solution you'd like**
I would like to see the error bars of `plot1d` and the gray area of `plotratio` to be increased to account for the total of systematic and statistical uncertainties. I think it would be enough to have them added in quadrature in order to compute the total, but a more rigorous method might exist.
I see multiple different solutions to make this work:

- Return the value of the statistical error computed in the plot functions and allow the user to change the size of the errors after plotting, so that the user can manually add systematic uncertainties.
- Add a parameter to the plot functions that allows the user to provide an array with one entry for each bin. This array is added to the statistical uncertainty inside the plot functions.
- Let the `Hist` class keep track of systematic uncertainties in some way.

What do you think would be the right thing to go with?

**Comment by andrzejnovak** [comment]
I think this might out of scope for `coffea.hist`, I am not sure how it would automatically track systematics. I agree that a plotting method like that would be useful and should probably be in `mplhep`. The interesting question I think is for @henryiii if `hist` histograms could hold two kinds of errors, these could then be set manually from various results in coffea and dumped into the plotting method as two histograms.

**Comment by nsmith-** [comment]
I think it would be nice for future tools to have some convenient way of specifying external error bands, e.g. envelope of variations along some systematic axis in a multi-D histo, or linear/quadrature sum of up/down fluctuations. I wonder if we need to define a convention for a special "systematic" axis type since there is a semantic meaning to the "Up" and "Down" variations that needs to be respected.
One reminder, often the a-priori systematics are not so meaningful anyway and the most interesting plots are a-posteriori (i.e. post-fit) so making a routine that interfaces with your favorite fitting package will be more useful in the long run (and will solve this problem at the same time)

**Comment by nsmith-** [comment]
Something to follow up on in [scikit-hep/mplhep](https://github.com/scikit-hep/mplhep).
