### ISSUE TITLE
Fixing colors to samples in plot1d

### ISSUE THREAD

**Issue by jeffkrupa** [scikit-hep/coffea#347]
**Is your feature request related to a problem? Please describe.**
By default, it seems the color order of stacked+overlayed processes in `plot1d` is fixed by yield. This makes side-by-side yield comparison of histograms difficult, particularly when one tries to compare individual process yield in a histogram (since if the yield order changes, the color also changes, instead of the color being fixed to a particular sample, so you can't easily compare side-by-side). 

**Describe the solution you'd like**
I would like to have functionality for `plot1d` to create plots where both: 
1. processes are overlayed and stacked are ordered by yield (exists)  
2. specific colors are fixed to specific samples (to my knowledge does not exist)

Perhaps this could be passed as an option in `plot1d`.

**Comment by nsmith-** [comment]
A note, probably the reason they are ordered by yield is because somewhere else the sorting of the axis is set to `integral`, see https://coffeateam.github.io/coffea/api/coffea.hist.Cat.html#coffea.hist.Cat
If you change the `myhisto.axis("axisname").sorting = "identifier"` it will be alphabetical, for example, and hence the coloring will be consistent for all plots since the mpl color cycler is always iterated through in the same order. That said, there's no interface at present to re-arrange the axis ordering, and also no method to have a consistent coloring (i.e. not dictated by the mpl color cycler) when using `integral` ordering. I think these would be good additions to have.

**Comment by lgray** [comment]
Since this is a major style / book-keeping issue, we should advertise it in the Hist constructor for ease of use.

**Comment by andrzejnovak** [comment]
I'm torn whether this is an oversight or it starts to go into the territory of custom plotting. But yeah I would expect it to be possible at least to plot in the order of identifiers

**Comment by andrzejnovak** [comment]
@jeffkrupa did you find out if @nsmith- 's suggestion works for you?

**Comment by jeffkrupa** [comment]
@andrzejnovak @nsmith- thank you for your responses! ideally, I would be able to order a stacked histogram by integral and fix colors to specific processes. While ordering by identifier solves the color problem, it makes it more difficult in my opinion to glean important information from the histogram, such as the relative sizes of backgrounds

**Comment by andrzejnovak** [comment]
Ok, I don't actually know how we would implement this generally enough (should work for any kwarg right, not just color).

The way to get what you want within the coffea plotting helpers is to have a dict of key:color combinations and fetch from this dict based on the order of the identifiers in the hist. You should be able to pass the list you create like that to `"color"` in `fill_opts`. The ordering should not be adjusted in the plotting fcn, so this should have the desired effect

But really at that point, you are better off writing your own plotting fcn, for example something like this: https://gist.github.com/matthewfeickert/e93378afaf33f56c7287f37b0782a221

**Comment by lgray** [comment]
So going back through issues recently, there are a few such issues where there's something pretty useful/convenient that's not generalizable but work well enough if you agree to certain conventions.

I think it is fundamentally useful to collect things like this, because I'm quite certain people asking for these features are not alone, and we want to reduce the amount of copy/pasta running around.

To that end - perhaps we should have a contrib sub-package in coffea?

I'd be thinking of this in the django style of contrib, which are things that need non-private access to coffea/awkward/mplhep.

**Comment by andrzejnovak** [comment]
I thought medium to long term you expect coffea to fill `hist` histograms, which is where this could be discussed. IMO coffea should be exporting to easily plottable format, rather than handling the plotting because otherwise, you end up writing something much more complex than is being solved.

In this particular case `coffea.histogram` -> coupled lists of histgrams/binnings/identifiers -> `mplhep.histplot` and you can sort it any way you like and fetch assigned kwargs by key from dicts on the side. I think that's better than designing a specific coffea plotting API.

**Comment by lgray** [comment]
Concerning hist - we do, and I think what you pose as a solution is the right way to go. It'll be a post 0.7.0 development unless you make a good reason on #396. It may mark 0.8.0 since I imagine there will be breaking changes at some level, or backwards compatibility will be a pain.

Thinking about it, making the plotting interface in coffea as thin as possible, approaching what you're suggesting, would be a good extension of the 0.7.0 targets.

More generally, I wasn't proposing an interface but rather a place where people can put recipes for specific useful behaviors so there's not a parallel ecosystem of twikis and gists.
By accumulating those it can help inform further development in dependent packages, and we can update/deprecate contrib items accordingly.

I think a contrib area thing makes a lot of sense from that perspective as typically these recipes involve assumptions about inputs or available packages.

**Comment by andrzejnovak** [comment]
`hist` should be solving this once https://github.com/scikit-hep/hist/pull/243 gets done
