### ISSUE TITLE
Add recoverable option implementation for dask

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#515]
This is a more general solution to #317 and #443.

@jrueb @andrzejnovak 

Add a new opt-in feature that lets us always finish jobs, and reports failed chunks in a way that can be resubmitted and easily bookkept.

* reports files/chunks of bad jobs, instead returning a list of chunks and reasons in the `metrics` accumulator, always completes
* has some basic quality metrics to let people know if it's worth rerunning 
  * i.e. easy to know if fail chunks / total chunks for a dataset is small

In the future: 
* returned list of failed chunks can be given to `run_uproot_job` to be rerun. (optional for now, may need more aggressive changes)

**Comment by andrzejnovak** [comment]
Few points from recent experiences
- dask and parsl handle submission differently, which is not gonna be apparent to a new user and they have different caveats
  - dask submits reduce jobs, but for non-trivial accumulator sizes, these might need much more memory than the default processing job, so dask is stuck in last few percent just trying to resubmit them
  - parsl doesn't submit reduce jobs, instead, all chunks are added on the submit node which becomes a problem with more inputs files e.g. in my case 40k files/chunks the processing itself is a fraction of the total runtime (10%) and the rest is spent on the submit node just merging accumulators, the memory problem doesn't hit in this case since the submit node doesn't share resources, but it could be a problem if the submit node was weaker

**Comment by andrzejnovak** [comment]
- executors could automatically save intermediate output if the accumulator grows too large for memory
  - maybe just warn by default, with an opt in flag

**Comment by andrzejnovak** [comment]
This is now available in futures/parsl as `recoverable=True`

**Comment by lgray** [comment]
This will be fixed in coffea 2023 with the report option that'll be available in uproot/dask-awkward.
