### ISSUE TITLE
Weights discussion

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#60]
Continuing the discussion from #59  that doesn't belong there.

**Comment by mcremone** [comment]
@areinsvo yes, that's exactly what I mean, thanks for summarizing it far better than I did :)

@lgray regarding "we cannot pass jagged arrays to numpy.searchsorted", yeah we know and in fact I think that @areinsvo meant that we should do "something" to make this work even when we have jagged arrays, to go around this limitation.

But if I understand correctly this other statement "If a jagged array is passed in, the evaluator machinery handles flattening the inputs to numpy arrays and re-jaggifying the outputs based on the input structure."  you have already done this "something". Can you point us to the parts of the code that deals with this?

Finally, wouldn't be best to have jagged searchsorted and similar included in, let's say, awkward?

**Comment by lgray** [comment]
@mcremone It's in the base class.

https://github.com/CoffeaTeam/fnal-column-analysis-tools/blob/master/fnal_column_analysis_tools/lookup_tools/lookup_base.py

Search sorted doesn't belong in awkward, my opinion. I don't think we're ever going to have jagged bins in each event with a jagged set of values to look up, i.e. the weight table itself is never jagged. 

The only thing that is jagged are the data that are being supplied to the search where there's no problem with it just being flattened as far as workflow goes. 

Moreover if you pass multiple jagged arrays as part of a lookup you need to spend some time first making sure they have the structure and then iterate over the bins to begin with. 

Finally, search sorted will only return numpy arrays. So you have to wrap the output back up anyway.

I think machinery is justified.

**Comment by nsmith-** [comment]
There is a broad class of non-ufunc numpy functions that cannot upcast to awkward arrays because the numpy library does not have hooks to pass control up to the derived type, as it does for [ufuncs](https://docs.scipy.org/doc/numpy-1.14.1/neps/ufunc-overrides.html).  The options are either to implement manually an `awkward.func` for every `numpy.func` that we can think of, or handle case-by-case in helper classes such as this.  The boilerplate to do this is not insignificant, and in fact what we have in `lookup_base` is not yet sufficient to support all awkward arrays (although I did put in checks to make sure it either works correctly or errors out.)  Perhaps @jpivarski has some thoughts on the best way to do this.

**Comment by nsmith-** [comment]
One attractive option is to isolate the boilerplate into awkward.  In fact a full-depth `flatten()` (in addition to the current one-level-at-a-time version) and a companion `reconstitute()` function would provide a general solution.  For non-ufunc operations that can accept a `where` syntax, there is room for some optimization as well by returning an appropriate mask to view the underlying content of the awkward array and avoiding the copy where applicable.

**Comment by lgray** [comment]
very stale.
