### ISSUE TITLE
Tracking issue for common tasks in awkward we've put in functions in coffea.

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#655]
Here's one example from the recent systematics PR. We should find more snippets like this and collect them for a PR to awkward itself so that we don't worry about its details so much.

```python3
def awkward_rewrap(arr, like_what, gfunc):
    behavior = awkward._util.behaviorof(like_what)
    func = partial(gfunc, data=arr.layout)
    layout = awkward.operations.convert.to_layout(like_what)
    newlayout = awkward._util.recursively_apply(layout, func)
    return awkward._util.wrap(newlayout, behavior=behavior)
```

@nsmith- @jpivarski

**Comment by jpivarski** [comment]
That would be this: scikit-hep/awkward-1.0#516, and yeah, it's high time we did that.

The v1 `recursively_apply` and `broadcast_and_apply` interfaces are weird because they were developed as we went along. They were made more consistent with themselves and with each other in v2. It would be really, really, really nice to only expose the v2 interface before this becomes public.

**Comment by lgray** [comment]
Fixed in awkward2 some time ago.

**Comment by nsmith-** [comment]
Specifically with `ak.transform` I believe?

**Comment by lgray** [comment]
Exactly, it's exposed better through that function now. Though we still do it the old way in a few places in coffea.
