### ISSUE TITLE
Dask Nanoevents attributes rely on possibly dead weakref of original array

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/coffea#823]
**Describe the bug**
Several attributes of NanoEvents when used with Dask rely on the weakref `__original_array__` inside the behavior. However, if the weakref is dead because the user did not keep a reference to the original array, the attribute will fail.

**To Reproduce**
```python
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

events = NanoEventsFactory.from_root(
    "https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root",
    metadata={"dataset": "nano_dy"},
    schemaclass=NanoAODSchema,
    permit_dask=True,
).events()
events = events[0:5]
parent = events["GenPart"].parent
```
The last line will raise an error `AttributeError: 'NoneType' object has no attribute 'GenPart'`

Coffea version 2023.5.0.rc0

**Comment by lgray** [comment]
Thanks for reporting this I'll see if I can make a workaround. The behaviors shouldn't be getting pickled for this, which is the only way that ref should be None as far as I know, so I'm surprised you're hitting a problem when slicing.

That being said: Slicing is being worked on in dask-awkward. In particular keeping the type tracer array, that the behaviors are stored in, stable appears to be a bit of a problem. I'll need to wait for that to get settled before a there's a proper fix.

You might want to see if you can distill this down into a pure dask_awkward problem. 

Reliance on a weakref on the user side for coffea is a necessity, since it's the only way to have self-referential task graph building without needing to pickle the dask-awkward array itself.

**Comment by jrueb** [comment]
Do you mean dask_awkward should be keeping a strong reference?
The only strong reference seems to be the user level `events`. Hence getting rid of `events` in any way will trigger this issue. For example
```python
genpart = events["GenPart"]
del events
parent = genpart.parent
```
has the same effect even without slicing.

**Comment by lgray** [comment]
Oh, that's interesting.

I'll see what I can do to resolve that. In the mean time does slicing without reassigning work?

```python3
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema

events = NanoEventsFactory.from_root(
    "https://github.com/CoffeaTeam/coffea/raw/master/tests/samples/nano_dy.root",
    metadata={"dataset": "nano_dy"},
    schemaclass=NanoAODSchema,
    permit_dask=True,
).events()
sliced = events[0:5]
parent = sliced["GenPart"].parent
```
?

**Comment by jrueb** [comment]
Yes, without reassigning works. The reference count is not decreased without the reassignment and thus the weakref is not dead.

**Comment by lgray** [comment]
Thanks - that should help in remedying the situation. Dask will follow strong references and try to serialize them, we specifically don't want that to happen in this case.

**Comment by nsmith-** [comment]
The old trick to always keep the factory alive was to hide it in the behavior: https://github.com/CoffeaTeam/coffea/blob/075fc00dfd2f16c1f1edbeb20152e73940f70c67/coffea/nanoevents/factory.py#L387
as the behavior passes down through all awkward ops. So I'd guess the root cause is a missing behavior stickyness?
